# Generated by Django 5.2.12 on 2026-03-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='role',
            field=models.CharField(max_length=200),
        ),
    ]
